/**
 * ABI Exports for SPBU Diamond Contract Facets
 * Auto-generated by scripts/export-abis.js
 */

// Import all facet ABIs
import AccessControlFacetABI from './AccessControlFacet.json';
import IdentityMemberFacetABI from './IdentityMemberFacet.json';
import IdentityNotifFacetABI from './IdentityNotifFacet.json';
import OrganizationFacetABI from './OrganizationFacet.json';
import HumanCapitalFacetABI from './HumanCapitalFacet.json';
import AssetCoreFacetABI from './AssetCoreFacet.json';
import AssetFileFacetABI from './AssetFileFacet.json';
import InventoryCoreFacetABI from './InventoryCoreFacet.json';
import InventoryDocsFacetABI from './InventoryDocsFacet.json';
import InventoryTransferFacetABI from './InventoryTransferFacet.json';
import LogisticCoreFacetABI from './LogisticCoreFacet.json';
import LogisticFileFacetABI from './LogisticFileFacet.json';
import AttendanceConfigFacetABI from './AttendanceConfigFacet.json';
import AttendanceRecordFacetABI from './AttendanceRecordFacet.json';
import PengadaanCoreFacetABI from './PengadaanCoreFacet.json';
import PengadaanPaymentFacetABI from './PengadaanPaymentFacet.json';
import PointOfSalesCoreFacetABI from './PointOfSalesCoreFacet.json';
import PointOfSalesSalesFacetABI from './PointOfSalesSalesFacet.json';
import FinanceFacetABI from './FinanceFacet.json';
import QualityControlFacetABI from './QualityControlFacet.json';

// Import combined ABI
import DiamondCombinedABI from './DiamondCombined.json';

// Export all facet ABIs
export {
    AccessControlFacetABI,
    IdentityMemberFacetABI,
    IdentityNotifFacetABI,
    OrganizationFacetABI,
    HumanCapitalFacetABI,
    AssetCoreFacetABI,
    AssetFileFacetABI,
    InventoryCoreFacetABI,
    InventoryDocsFacetABI,
    InventoryTransferFacetABI,
    LogisticCoreFacetABI,
    LogisticFileFacetABI,
    AttendanceConfigFacetABI,
    AttendanceRecordFacetABI,
    PengadaanCoreFacetABI,
    PengadaanPaymentFacetABI,
    PointOfSalesCoreFacetABI,
    PointOfSalesSalesFacetABI,
    FinanceFacetABI,
    QualityControlFacetABI,
    DiamondCombinedABI,
};

// Export combined Diamond ABI as default
export default DiamondCombinedABI;
