/**
 * Script to extract ABIs from Hardhat artifacts and export to src/contracts/abis/
 * Run: node scripts/export-abis.js
 */

const fs = require('fs');
const path = require('path');

// List of deployed facets (matching deploy.js)
const DEPLOYED_FACETS = [
    'AccessControlFacet',
    'AssetCoreFacet',
    'AssetFileFacet',
    'AttendanceConfigFacet',
    'AttendanceRecordFacet',
    'CmsFacet',
    'FinanceFacet',
    'HumanCapitalFacet',
    'IdentityMemberFacet',
    'IdentityNotifFacet',
    'InventoryCoreFacet',
    'InventoryDocsFacet',
    'InventoryTransferFacet',
    'LogisticCoreFacet',
    'LogisticFileFacet',
    'OrganizationFacet',
    'PengadaanConfirmationFacet',
    'PengadaanCoreFacet',
    'PengadaanPaymentFacet',
    'PointOfSalesCoreFacet',
    'PointOfSalesSalesFacet',
    'QualityControlFacet',
];

const ARTIFACTS_DIR = path.join(__dirname, '..', 'artifacts', 'contracts', 'domains');
const OUTPUT_DIR = path.join(__dirname, '..', 'src', 'contracts', 'abis');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('🔧 Extracting ABIs from Hardhat artifacts...\n');

const allAbis = {};
const exportLines = [];

for (const facetName of DEPLOYED_FACETS) {
    const artifactPath = path.join(ARTIFACTS_DIR, `${facetName}.sol`, `${facetName}.json`);

    if (!fs.existsSync(artifactPath)) {
        console.log(`❌ Artifact not found: ${facetName}`);
        continue;
    }

    try {
        const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
        const abi = artifact.abi;

        // Filter out constructor and fallback functions
        const filteredAbi = abi.filter(item =>
            item.type === 'function' || item.type === 'event'
        );

        // Write individual ABI file
        const abiFileName = `${facetName}.json`;
        const abiFilePath = path.join(OUTPUT_DIR, abiFileName);
        fs.writeFileSync(abiFilePath, JSON.stringify(filteredAbi, null, 2));

        allAbis[facetName] = filteredAbi;
        exportLines.push(`export { default as ${facetName}ABI } from './${abiFileName}';`);

        const functionCount = filteredAbi.filter(i => i.type === 'function').length;
        const eventCount = filteredAbi.filter(i => i.type === 'event').length;
        console.log(`✅ ${facetName}: ${functionCount} functions, ${eventCount} events`);

    } catch (error) {
        console.log(`❌ Error processing ${facetName}: ${error.message}`);
    }
}

// Create combined ABI (all functions from all facets)
const combinedAbi = Object.values(allAbis).flat();
const combinedPath = path.join(OUTPUT_DIR, 'DiamondCombined.json');
fs.writeFileSync(combinedPath, JSON.stringify(combinedAbi, null, 2));

// Create index.ts for easy imports
const indexContent = `/**
 * ABI Exports for SPBU Diamond Contract Facets
 * Auto-generated by scripts/export-abis.js
 */

// Import all facet ABIs
${DEPLOYED_FACETS.map(name => `import ${name}ABI from './${name}.json';`).join('\n')}

// Import combined ABI
import DiamondCombinedABI from './DiamondCombined.json';

// Export all facet ABIs
export {
${DEPLOYED_FACETS.map(name => `    ${name}ABI,`).join('\n')}
    DiamondCombinedABI,
};

// Export combined Diamond ABI as default
export default DiamondCombinedABI;
`;

fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), indexContent);

console.log(`\n📦 Combined ABI: ${combinedAbi.length} items`);
console.log(`\n✅ ABIs exported to: ${OUTPUT_DIR}`);
console.log('📄 Files created:');
console.log(`   - ${DEPLOYED_FACETS.length} individual facet ABIs`);
console.log('   - DiamondCombined.json (all ABIs merged)');
console.log('   - index.ts (TypeScript exports)');
